export var scene;
export var camera;
export var renderer;
export var orbit;
export var shapes = [];
export var xygrid = [];
export var yzgrid= [];
export var xzgrid = [];
export var dragx = [];
export var dragy = [];
export var dragz = [];
export var two_plane;
export var two_geometry;
export var first_time = 1;
export var is_2D = 0;
export var arrowHelper = [];